/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'react-native-flux-desktop.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./react-native-flux-desktop.android-arm64.node')
          } else {
            nativeBinding = require('react-native-flux-desktop-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'react-native-flux-desktop.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./react-native-flux-desktop.android-arm-eabi.node')
          } else {
            nativeBinding = require('react-native-flux-desktop-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'react-native-flux-desktop.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./react-native-flux-desktop.win32-x64-msvc.node')
          } else {
            nativeBinding = require('react-native-flux-desktop-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'react-native-flux-desktop.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./react-native-flux-desktop.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('react-native-flux-desktop-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'react-native-flux-desktop.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./react-native-flux-desktop.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('react-native-flux-desktop-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'react-native-flux-desktop.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./react-native-flux-desktop.darwin-universal.node')
      } else {
        nativeBinding = require('react-native-flux-desktop-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'react-native-flux-desktop.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./react-native-flux-desktop.darwin-x64.node')
          } else {
            nativeBinding = require('react-native-flux-desktop-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'react-native-flux-desktop.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./react-native-flux-desktop.darwin-arm64.node')
          } else {
            nativeBinding = require('react-native-flux-desktop-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'react-native-flux-desktop.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./react-native-flux-desktop.freebsd-x64.node')
      } else {
        nativeBinding = require('react-native-flux-desktop-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'react-native-flux-desktop.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./react-native-flux-desktop.linux-x64-musl.node')
            } else {
              nativeBinding = require('react-native-flux-desktop-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'react-native-flux-desktop.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./react-native-flux-desktop.linux-x64-gnu.node')
            } else {
              nativeBinding = require('react-native-flux-desktop-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'react-native-flux-desktop.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./react-native-flux-desktop.linux-arm64-musl.node')
            } else {
              nativeBinding = require('react-native-flux-desktop-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'react-native-flux-desktop.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./react-native-flux-desktop.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('react-native-flux-desktop-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'react-native-flux-desktop.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./react-native-flux-desktop.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('react-native-flux-desktop-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'react-native-flux-desktop.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./react-native-flux-desktop.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('react-native-flux-desktop-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'react-native-flux-desktop.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./react-native-flux-desktop.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('react-native-flux-desktop-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'react-native-flux-desktop.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./react-native-flux-desktop.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('react-native-flux-desktop-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'react-native-flux-desktop.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./react-native-flux-desktop.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('react-native-flux-desktop-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { clipboardText, setClipboardText, GpuImage, releaseGpuImage, GpuCtx2D, kvOpen, kvIsOpen, kvClose, kvPut, kvGet, kvHas, kvDel, kvKeys, kvCompact, armWatch, disarmWatch, presentGpu, present, setBackground, pump, createTray, setTrayIcon, setTrayTooltip, removeTray, createWindow, closeWindow, setWindowIcon, setAppUserModelId, setCursor, setTitle, setResizable, isResizable, setMinSize, setMaxSize, setSize, getInnerSize, setDecorations, isDecorated, setMaximized, isMaximized, setMinimized, focusWindow, centerWindow, setWindowPosition, getMonitorSize, getOuterPosition, getScale, version } = nativeBinding

module.exports.clipboardText = clipboardText
module.exports.setClipboardText = setClipboardText
module.exports.GpuImage = GpuImage
module.exports.releaseGpuImage = releaseGpuImage
module.exports.GpuCtx2D = GpuCtx2D
module.exports.kvOpen = kvOpen
module.exports.kvIsOpen = kvIsOpen
module.exports.kvClose = kvClose
module.exports.kvPut = kvPut
module.exports.kvGet = kvGet
module.exports.kvHas = kvHas
module.exports.kvDel = kvDel
module.exports.kvKeys = kvKeys
module.exports.kvCompact = kvCompact
module.exports.armWatch = armWatch
module.exports.disarmWatch = disarmWatch
module.exports.presentGpu = presentGpu
module.exports.present = present
module.exports.setBackground = setBackground
module.exports.pump = pump
module.exports.createTray = createTray
module.exports.setTrayIcon = setTrayIcon
module.exports.setTrayTooltip = setTrayTooltip
module.exports.removeTray = removeTray
module.exports.createWindow = createWindow
module.exports.closeWindow = closeWindow
module.exports.setWindowIcon = setWindowIcon
module.exports.setAppUserModelId = setAppUserModelId
module.exports.setCursor = setCursor
module.exports.setTitle = setTitle
module.exports.setResizable = setResizable
module.exports.isResizable = isResizable
module.exports.setMinSize = setMinSize
module.exports.setMaxSize = setMaxSize
module.exports.setSize = setSize
module.exports.getInnerSize = getInnerSize
module.exports.setDecorations = setDecorations
module.exports.isDecorated = isDecorated
module.exports.setMaximized = setMaximized
module.exports.isMaximized = isMaximized
module.exports.setMinimized = setMinimized
module.exports.focusWindow = focusWindow
module.exports.centerWindow = centerWindow
module.exports.setWindowPosition = setWindowPosition
module.exports.getMonitorSize = getMonitorSize
module.exports.getOuterPosition = getOuterPosition
module.exports.getScale = getScale
module.exports.version = version
