/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 读系统剪贴板文本（粘贴用）。剪贴板为空或非文本时返回空串（上层据此判无内容）。 */
export declare function clipboardText(): string
/** 写系统剪贴板文本（复制/剪切用）。失败静默（返回 false）。 */
export declare function setClipboardText(text: string): boolean
/** grabPixels 回读结果（napi object，供 JS 侧拼 PNG）。 */
export interface GrabResult {
  width: number
  height: number
  rgba: Buffer
}
/** 释放图片缓存。 */
export declare function releaseGpuImage(id: number): void
/** 打开（或复用）一个命名存储。幂等：同名已开则直接返回。 */
export declare function kvOpen(name: string, path: string): void
export declare function kvIsOpen(name: string): boolean
export declare function kvClose(name: string): void
/** 写一条：value 是上层编码好的字节（含类型前缀）。 */
export declare function kvPut(name: string, key: string, value: Buffer): void
/** 读一条原始字节；不存在返回 null。 */
export declare function kvGet(name: string, key: string): Buffer | null
export declare function kvHas(name: string, key: string): boolean
export declare function kvDel(name: string, key: string): boolean
export declare function kvKeys(name: string): Array<string>
/** 手动压缩（重写实体文件）。上层可择时调用；写放大超阈值时也可自动做，这里先提供显式入口。 */
export declare function kvCompact(name: string): void
/**
 * 装填监听：rect 为菜单在屏幕上的物理矩形（上层把逻辑 x/y/宽/高 × scale 取整得到）。
 * on_dismiss：命中「外面按下」时经 tsfn 回抛一次（payload 固定字符串 "dismiss"）。
 * 重复 arm 会先解除旧的。非 Windows 下仅记回调不轮询。
 */
export declare function armWatch(rectX: number, rectY: number, rectW: number, rectH: number, onDismiss: (...args: any[]) => any): void
/** 解除监听（菜单因选中项/失焦等正常关闭时调用，幂等）。 */
export declare function disarmWatch(): void
/**
 * 把 Skia 画好的 RGBA 贴到指定窗口（GPU 路径）。
 * 像素经 write_pixels 上传到 Ganesh surface，然后 flush + swap_buffers 直呈。
 */
export declare function presentGpu(id: number, buf: Buffer, srcW: number, srcH: number): void
/**
 * 把 Skia 画好的 RGBA 贴到指定窗口。buf 为 src_w×src_h 原始 RGBA；
 * 目标帧缓冲固定为该窗物理尺寸 entry.size。不一致则最近邻缩放（dpr 封顶靠这条）。
 */
export declare function present(id: number, buf: Buffer, srcW: number, srcH: number): void
/**
 * 设置指定窗口的背景色（RGB 0..=255）：仅存进 Entry.bg，供拖动缩放时填充露出区域（见 blit_placeholder）。
 * 不立即重绘（避免擦掉当前内容）；由 TS 侧按主题同步（暗 #141414 / 亮 #ffffff）。
 */
export declare function setBackground(id: number, r: number, g: number, b: number): void
/**
 * 非阻塞地推进全局底座事件队列一次；由 PumpCoordinator 的单一定时器反复调用。
 * 返回 true 仅当事件循环已消失（尚未 create 或已异常）——正常多窗生命周期里保持 false。
 */
export declare function pump(): boolean
/**
 * 创建托盘。icon_rgba 为 RGBA8（长度须 = w*h*4，JS 侧用 @napi-rs/canvas 解码 PNG 得到，同 set_window_icon）。
 * tooltip 悬浮提示。已存在则先摘除重建。不挂原生菜单（见文件头说明）。
 */
export declare function createTray(onEvent: (...args: any[]) => any, iconRgba: Buffer, w: number, h: number, tooltip: string): void
/** 换托盘图标（RGBA8）。 */
export declare function setTrayIcon(iconRgba: Buffer, w: number, h: number): void
/** 换托盘悬浮提示文本。 */
export declare function setTrayTooltip(text: string): void
/** 摘除托盘：drop 句柄即从通知区移除，并清空 tsfn 停止回抛。 */
export declare function removeTray(): void
/**
 * 创建一扇新窗口 + surface，返回窗口 id（u32）。事件循环全局懒建复用：
 *   首窗懒建 EventLoop 并设 Poll；后续窗只 build 新 Window 挂到同一条循环。
 *   不阻塞：之后由 JS 定时器反复调用 pump() 驱动事件处理（ PumpCoordinator 统一泵）。
 * x/y 为可选的逻辑坐标（缺省由 OS 层叠摆放）。
 */
export declare function createWindow(width: number, height: number, title: string, x: number | undefined | null, y: number | undefined | null, onTop: boolean | undefined | null, decorations: boolean | undefined | null, transparent: boolean | undefined | null, maximized: boolean | undefined | null, onEvent: (...args: any[]) => any): number
/**
 * 隐藏并摘除一扇窗口：set_visible(false) + 从 map remove（顺带 drop 其 Surface 像素内存）。
 * 不真 drop Window（&'static leak，避免 Surface 引用悬垂）。末窗退出由 TS 侧 liveWindows 处理。
 */
export declare function closeWindow(id: number): boolean
/**
 * 设置指定窗口的图标（标题栏 + 任务栏按钮）。Windows 下若窗口未设图标，
 * 任务栏会回退到「进程主 exe 的图标」——打包运行即 node.exe 的绿色六边形，故必须显式设。
 * rgba 为底座 Icon 要求的 RGBA8（长度须 = width*height*4），由 JS 侧用 canvas 解码 PNG 得到。
 */
export declare function setWindowIcon(id: number, rgba: Buffer, width: number, height: number): void
/**
 * 取某扇窗的 Win32 HWND（以 i64 交出）。与 WebView 无关的通用能力：把窗口原生句柄交给
 * 外部「view 渲染模块」（如可选的 webview 包）在其上挂子面。非 Windows 或取不到返回 0。
 * 走 raw-window-handle 0.5 的 HasRawWindowHandle（主库已依赖，gpu 亦用之）。
 */
export declare function getHwnd(id: number): number
/**
 * 设置当前进程的 AppUserModelID（AUMID），须在创建任何窗口之前调用一次。
 * 为什么需要：Windows 任务栏按 AUMID 归组，未显式设置时回退到「进程主 exe」= node.exe，
 * 于是任务栏按钮固定显示 node 的绿色图标——此时 WM_SETICON（set_window_icon）能改标题栏却改不动
 * 归组后的任务栏按钮。给进程一个独立 AUMID 后，按钮才会采用我们为窗口设置的图标。
 */
export declare function setAppUserModelId(id: string): void
/** 设置指定窗口光标形状：JS 传 cursor-icon 规范名，由 cursor_icon 的 FromStr 解析，未知名回退 Default。 */
export declare function setCursor(id: number, shape: string): void
/** 改指定窗口标题（调试/状态展示用） */
export declare function setTitle(id: number, title: string): void
/** 设/取消指定窗口是否允许用户拖拽缩放。 */
export declare function setResizable(id: number, resizable: boolean): void
/** 查询指定窗口当前是否可缩放（无窗按默认可缩放 true）。 */
export declare function isResizable(id: number): boolean
/** 设最小内尺寸（逻辑像素）；传 null 表示该维不设，两维都 null = 清除最小限制。 */
export declare function setMinSize(id: number, width?: number | undefined | null, height?: number | undefined | null): void
/** 设最大内尺寸（逻辑像素）；传 null 表示该维不设，两维都 null = 清除最大限制。 */
export declare function setMaxSize(id: number, width?: number | undefined | null, height?: number | undefined | null): void
/** 以逻辑像素设定指定窗口的内尺寸（内容区大小）。 */
export declare function setSize(id: number, width: number, height: number): void
/** 指定窗口当前内尺寸（逻辑像素）：返回 [w, h]；无窗返回 [0, 0]。 */
export declare function getInnerSize(id: number): Array<number>
/** 设/取消指定窗口的标题栏与边框（decorations）：false = 无标题无边框。 */
export declare function setDecorations(id: number, decorations: boolean): void
/** 查询指定窗口当前是否有标题栏/边框（无窗按 true 兜底）。 */
export declare function isDecorated(id: number): boolean
/** 设/取消指定窗口最大化（true 铺满工作区，false 还原到之前尺寸）。 */
export declare function setMaximized(id: number, maximized: boolean): void
/** 查询指定窗口当前是否处于最大化（无窗按 false）。 */
export declare function isMaximized(id: number): boolean
/** 最小化 / 从最小化恢复指定窗口（true 最小化到任务栏，false 恢复显示）。 */
export declare function setMinimized(id: number, minimized: boolean): void
/**
 * 唤醒并前置指定窗口：先从最小化恢复（set_minimized(false)），再请求前台焦点（focus_window）。
 * 用于「打包后重复打开 → 唤起老 App」：次实例经 IPC 通知主实例，主实例调本函数把主窗带回前台。
 */
export declare function focusWindow(id: number): void
/**
 * 把指定窗口在主显示器上居中：用外框尺寸（含标题栏/边框）与显示器物理尺寸求左上角，
 * 坐标兜底不小于 0（负坐标会被 OS 挪回屏内）。取不到显示器时静默返回 Ok。
 */
export declare function centerWindow(id: number): void
/** 以逻辑坐标把指定窗口移动到 (x, y)（左上角）。 */
export declare function setWindowPosition(id: number, x: number, y: number): void
/**
 * 指定窗口所在主显示器尺寸与原点（逻辑像素）：返回 [originX, originY, width, height]；
 * 无窗或取不到显示器返回 [0, 0, 0, 0]（上层据此判不可用）。
 */
export declare function getMonitorSize(id: number): Array<number>
/** 指定窗口外框左上角当前坐标（逻辑像素）：返回 [x, y]；无窗或系统不支持返回 [0, 0]。 */
export declare function getOuterPosition(id: number): Array<number>
/** 指定窗口的当前 DPI 缩放因子 */
export declare function getScale(id: number): number
export declare function version(): string
export type NapiGpuImage = GpuImage
/** GPU 图片包装。构造时传入 RGBA 像素，返回 id 供 drawImage 使用。 */
export declare class GpuImage {
  id: number
  constructor(width: number, height: number, rgba: Buffer)
}
export type NapiGpuCtx2D = GpuCtx2D
/** GPU Canvas2D 上下文。JS：const ctx = new GpuCtx2D(winId); ctx.fillRect(...) 等。 */
export declare class GpuCtx2D {
  constructor(id: number)
  set fillStyle(val: string)
  set strokeStyle(val: string)
  set lineWidth(val: number)
  set globalAlpha(val: number)
  set lineCap(val: string)
  set lineJoin(val: string)
  setLineDash(segments: Array<number>): void
  save(): void
  restore(): void
  translate(x: number, y: number): void
  scale(sx: number, sy: number): void
  rotate(angle: number): void
  resetTransform(): void
  setTransform(a: number, b: number, c: number, d: number, e: number, f: number): void
  /**
   * canvas transform(a,b,c,d,e,f)：累积左乘 current = current × arg（区别于 setTransform 的替换）。
   * painter.ts 每帧用 flatten 出的矩阵经此叠加到 dpr 基准矩阵上。
   */
  transform(a: number, b: number, c: number, d: number, e: number, f: number): void
  fillRect(x: number, y: number, w: number, h: number): void
  strokeRect(x: number, y: number, w: number, h: number): void
  clearRect(x: number, y: number, w: number, h: number): void
  beginPath(): void
  moveTo(x: number, y: number): void
  lineTo(x: number, y: number): void
  arcTo(x1: number, y1: number, x2: number, y2: number, radius: number): void
  arc(x: number, y: number, radius: number, startAngle: number, endAngle: number, counterclockwise?: boolean | undefined | null): void
  quadraticCurveTo(cpx: number, cpy: number, x: number, y: number): void
  bezierCurveTo(cp1X: number, cp1Y: number, cp2X: number, cp2Y: number, x: number, y: number): void
  closePath(): void
  fill(): void
  stroke(): void
  clip(): void
  fillSvgPath(d: string, evenOdd: boolean): void
  strokeSvgPath(d: string): void
  set font(val: string)
  setTextBaseline(val: string): void
  fillText(text: string, x: number, y: number): void
  strokeText(text: string, x: number, y: number): void
  measureText(text: string): number
  drawImage(imgId: number, dx: number, dy: number, dw?: number | undefined | null, dh?: number | undefined | null): void
  /** 提交 GPU 绘制 + swap_buffers 直呈。 */
  flush(): void
  /** 仅提交 GPU 命令到后备缓冲、不 swap_buffers（供离屏回读抓帧用，避开双缓冲时序）。 */
  flushSubmit(): void
  /**
   * 【抓帧】flushSubmit 之后 glReadPixels 回读当前后备缓冲。
   * 返回 (物理宽, 物理高, RGBA)，行序已翻成自上而下（GL 原生自下而上），与肉眼/屏幕方向一致。
   */
  grabPixels(): GrabResult
  /** 【诊断】该窗口 Ganesh 资源缓存实际占用字节（图片纹理等 GPU 侧 native，V8 不可见）。 */
  cacheBytes(): number
  /** 清屏（背景色）。 */
  clearAll(r: number, g: number, b: number, a: number): void
}
